#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'pickingNumbers' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY a as parameter.
#

def pickingNumbers(a):
    # Write your code here
    high = 0
    for k in a:
        s1 = a.count(k)
        s2 = a.count(k-1) 
        high = max(high, s1+s2)
    return(high)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    a = list(map(int, input().strip().split(' ')))

    result = pickingNumbers(a)

    fptr.write(str(result) + '\n')

    fptr.close()
