#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the plusMinus function below.
def plusMinus(arr):
    p=0
    ng=0
    nul=0
    for i in range(len(arr)):
        if(arr[i]>0):
            p+=1
        elif(arr[i]==0):
            nul+=1
        else:
            ng+=1
    a = (p/len(arr))
    print(str.format('{0:.6f}', a))
    b = (ng/len(arr))
    print(str.format('{0:.6f}', b))
    c = (nul/len(arr))
    print(str.format('{0:.6f}', c))

if __name__ == '__main__':
    n = int(input())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
